<?php
declare(strict_types=1);
namespace Modules\Media\src;
use NovaNuke\Core\Admin\AdminMenuBuilding;use NovaNuke\Core\Media\MediaLibraryInterface;use NovaNuke\Core\Container\Container;use NovaNuke\Core\Http\Request;use NovaNuke\Core\Http\Response;use NovaNuke\Core\Modules\ModuleContext;use NovaNuke\Core\Modules\ModuleInterface;use NovaNuke\Core\View\ViewRenderer;
final class MediaModule implements ModuleInterface
{
 public function register(ModuleContext $x):void{$x->container->get(ViewRenderer::class)->addNamespace('media',$x->basePath.'/views');$x->container->bind(MediaRepository::class,static fn(Container$c)=>new MediaRepository($c->get(\PDO::class)));$x->container->bind(MediaLibraryInterface::class,static fn(Container$c)=>$c->get(MediaRepository::class));$x->container->bind(MediaUploadValidator::class,static fn()=>new MediaUploadValidator());$x->container->bind(MediaStorage::class,static fn()=>new MediaStorage(NOVANUKE_ROOT.'/public'));$x->container->bind(MediaManager::class,static fn(Container$c)=>new MediaManager($c->get(MediaRepository::class),$c->get(MediaUploadValidator::class),$c->get(MediaStorage::class),$c->get(\NovaNuke\Core\Events\EventDispatcher::class)));}
 public function boot(ModuleContext $x):void{$x->events->listen(\NovaNuke\Core\Events\EventName::ADMIN_MENU_BUILDING,static function(object$e):void{if($e instanceof AdminMenuBuilding)$e->add('media::title','/admin/media','media.manage','media','content');});$f=static fn(Container$c)=>new AdminMediaController($c->get(MediaRepository::class),$c->get(MediaManager::class),$c->get(\NovaNuke\Auth\AuthManager::class),$c->get(\NovaNuke\Core\Security\AuthorizationService::class),$c->get(\NovaNuke\Core\Logging\ActivityLogger::class),$c->get(\NovaNuke\Core\Security\CsrfTokenManager::class),$c->get(\NovaNuke\Core\Security\SessionManager::class),$c->get(ViewRenderer::class),$c->get(\NovaNuke\Core\I18n\Translator::class));$x->router->get('/admin/media',static fn(Request$r,Container$c):Response=>$f($c)->index());$x->router->post('/admin/media/upload',static fn(Request$r,Container$c):Response=>$f($c)->upload($r));$x->router->post('/admin/media/{id}/update',static fn(Request$r,Container$c):Response=>$f($c)->update($r));$x->router->post('/admin/media/{id}/delete',static fn(Request$r,Container$c):Response=>$f($c)->delete($r));}
}
