<?php

declare(strict_types=1);

namespace NovaNuke\Core\Developer;

use NovaNuke\Core\Version;
use RuntimeException;

final class ModuleScaffolder
{
    public function __construct(private readonly string $modulesPath)
    {
    }

    /** @return list<string> */
    public function create(string $name): array
    {
        $name = trim($name);
        if (! preg_match('/^[A-Za-z][A-Za-z0-9 ]{1,49}$/', $name)) {
            throw new RuntimeException('Module name must start with a letter and contain only letters, numbers and spaces.');
        }

        $class = str_replace(' ', '', ucwords(strtolower($name)));
        $slug = strtolower((string) preg_replace('/(?<!^)[A-Z]/', '-$0', $class));
        $path = rtrim($this->modulesPath, '/\\') . DIRECTORY_SEPARATOR . $class;
        if (file_exists($path)) {
            throw new RuntimeException("Module already exists: {$class}");
        }

        $directories = ['src', 'views', 'language', 'database/migrations', 'tests'];
        foreach ($directories as $directory) {
            if (! mkdir($path . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $directory), 0775, true)
                && ! is_dir($path . DIRECTORY_SEPARATOR . $directory)) {
                throw new RuntimeException("Unable to create module directory: {$directory}");
            }
        }

        $files = [];
        $files['module.json'] = json_encode([
            'name' => $class,
            'slug' => $slug,
            'version' => '1.0.0',
            'api_version' => '1.0',
            'description' => "{$class} module.",
            'author' => 'Your Name',
            'provider' => "Modules\\{$class}\\src\\{$class}Module",
            'cms_min_version' => Version::CURRENT,
            'php_min_version' => '8.3.0',
            'dependencies' => (object) [],
            'permissions' => ["{$slug}.manage"],
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n";
        $files["src/{$class}Module.php"] = $this->provider($class, $slug);
        $files['views/index.twig'] = "{% extends \"layouts/default.twig\" %}\n{% block title %}{$class} — NovaNuke{% endblock %}\n{% block content %}<section><h1>{$class}</h1><p>Your module is running.</p></section>{% endblock %}\n";
        $files['language/en.json'] = "{\n  \"title\": \"{$class}\"\n}\n";
        $files['language/es.json'] = "{\n  \"title\": \"{$class}\"\n}\n";
        $files['README.md'] = "# {$class}\n\nGenerated by `php bin/cms module:make \"{$name}\"`.\n\nStart in `src/{$class}Module.php`, keep routes and permissions namespaced with `{$slug}.`, and add schema changes under `database/migrations/`. See `docs/MODULES.md`.\n";

        $written = [];
        foreach ($files as $relative => $contents) {
            $target = $path . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relative);
            if (file_put_contents($target, $contents) === false) {
                throw new RuntimeException("Unable to write scaffold file: {$relative}");
            }
            $written[] = $relative;
        }

        return $written;
    }

    private function provider(string $class, string $slug): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$class}\\src;

use NovaNuke\\Core\\Container\\Container;
use NovaNuke\\Core\\Http\\Request;
use NovaNuke\\Core\\Http\\Response;
use NovaNuke\\Core\\Modules\\ModuleContext;
use NovaNuke\\Core\\Modules\\ModuleInterface;
use NovaNuke\\Core\\View\\ViewRenderer;

final class {$class}Module implements ModuleInterface
{
    public function register(ModuleContext \$context): void
    {
        \$context->container->get(ViewRenderer::class)->addNamespace('{$slug}', \$context->basePath . '/views');
    }

    public function boot(ModuleContext \$context): void
    {
        \$context->router->get('/{$slug}', static function (Request \$request, Container \$container): Response {
            return Response::html(\$container->get(ViewRenderer::class)->render('@{$slug}/index.twig'));
        }, '{$slug}.index');
    }
}
PHP;
    }
}
