<?php

declare(strict_types=1);

namespace Modules\WebLinks\src;

use NovaNuke\Auth\AuthManager;use NovaNuke\Core\Content\ContentFormat;use NovaNuke\Core\Content\ContentProfile;use NovaNuke\Core\Content\ContentRendererInterface;use NovaNuke\Core\Http\Request;use NovaNuke\Core\Http\Response;use NovaNuke\Core\I18n\Translator;use NovaNuke\Core\Security\AuthorizationService;use NovaNuke\Core\Security\CsrfTokenManager;use NovaNuke\Core\Security\SessionManager;use NovaNuke\Core\View\ViewRenderer;use RuntimeException;use Twig\Markup;

final class PublicWebLinksController
{
    public function __construct(private readonly WebLinkRepository $links,private readonly WebLinkInput $input,private readonly WebLinkManager $manager,private readonly AuthManager $auth,private readonly CsrfTokenManager $csrf,private readonly SessionManager $session,private readonly ViewRenderer $views,private readonly AuthorizationService $authorization,private readonly ContentRendererInterface $contentRenderer,private readonly Translator $translator){}
    public function index(Request $r,?string $category=null):Response{if($category!==null&&!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$category))return Response::html($this->translator->translate('web-links::error.category_not_found'),404);$page=filter_var($r->query('page',1),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:1;$q=trim((string)$r->query('q',''));if(mb_strlen($q)>100)$q=mb_substr($q,0,100);$order=(string)$r->query('order','new');if(!in_array($order,['new','popular','title'],true))$order='new';$user=$this->auth->user();$result=$this->links->catalog((int)$page,$category,$q,$order,$user?(int)$user['id']:null);foreach($result['items']as&$item)$item['description_text']=trim(strip_tags($this->contentRenderer->render((string)$item['description'],ContentFormat::fromInput($item['description_format']??null),ContentProfile::Description)));unset($item);$manageUrl=$user!==null&&$this->authorization->allows((int)$user['id'],'web-links.manage')?'/admin/web-links':null;return Response::html($this->views->render('@web-links/index.twig',['result'=>$result,'categories'=>$this->links->categories(),'category'=>$category,'search'=>$q,'order'=>$order,'manage_url'=>$manageUrl]));}
    public function show(Request $r):Response{$link=$this->links->publicBySlug($this->slug($r->attribute('slug')));if($link===null)return Response::html($this->translator->translate('web-links::error.not_found'),404);$user=$this->auth->user();if(!$this->links->canView($link,$user?(int)$user['id']:null))return$user===null?Response::redirect('/login'):Response::html($this->translator->translate('web-links::error.unavailable_account'),403);$link['description_html']=new Markup($this->contentRenderer->render((string)$link['description'],ContentFormat::fromInput($link['description_format']??null),ContentProfile::Description),'UTF-8');$editUrl=$user!==null&&$this->authorization->allows((int)$user['id'],'web-links.manage')?'/admin/web-links/'.(int)$link['id'].'/edit':null;return Response::html($this->views->render('@web-links/show.twig',['link'=>$link,'csrf_token'=>$this->csrf->token(),'message'=>$this->session->pull('web-links.message'),'error'=>$this->session->pull('web-links.error'),'edit_url'=>$editUrl,'delete_url'=>$editUrl!==null?'/admin/web-links/'.(int)$link['id'].'/delete':null,'content_csrf_token'=>$editUrl!==null?$this->csrf->token():null,'delete_return_to'=>'/links']));}
    public function submitForm():Response{if($this->auth->user()===null)return Response::redirect('/login');return$this->submission();}
    public function submit(Request $r):Response{if($this->auth->user()===null)return Response::redirect('/login');if(!$this->csrf->validate($r->input('_token')))return Response::html($this->translator->translate('web-links::error.csrf'),419);try{$this->manager->submit($this->input->link($r->allInput(),false));$this->session->put('web-links.message',$this->translator->translate('web-links::message.submitted'));return Response::redirect('/links',303);}catch(RuntimeException $e){return$this->submission($r->allInput(),$this->error($e->getMessage()),422);}}
    public function visit(Request $r):Response{try{return Response::externalRedirect($this->manager->visit($this->slug($r->attribute('slug')),$r),302);}catch(RuntimeException|\InvalidArgumentException){return Response::html($this->translator->translate('web-links::error.not_found'),404);}}
    public function report(Request $r):Response{if(!$this->csrf->validate($r->input('_token')))return Response::html($this->translator->translate('web-links::error.csrf'),419);$return='/links';try{$slug=$this->slug($r->input('slug'));$id=$this->id($r->attribute('id'));$this->manager->report($id,$r);$this->session->put('web-links.message',$this->translator->translate('web-links::message.reported'));$return='/links/'.$slug;}catch(RuntimeException $e){$this->session->put('web-links.error',$this->error($e->getMessage()));}return Response::redirect($return,303);}
    private function submission(array $link=[],?string $error=null,int $status=200):Response{return Response::html($this->views->render('@web-links/submit.twig',['link'=>$link,'categories'=>$this->links->categories(),'csrf_token'=>$this->csrf->token(),'error'=>$error]),$status);}
    private function slug(mixed $v):string{$v=(string)$v;if(!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$v)||mb_strlen($v)>200)throw new RuntimeException('Invalid link.');return$v;}
    private function id(mixed $v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($id===false)throw new RuntimeException('Invalid link.');return(int)$id;}
    private function error(string $message):string{$keys=['Category not found.'=>'category_not_found','Link not found.'=>'not_found','This link is not available for your account.'=>'unavailable_account','Invalid or expired CSRF token.'=>'csrf','Invalid link.'=>'invalid_link','Sign in to submit a link.'=>'sign_in_submit','Too many submissions. Please wait before trying again.'=>'too_many_submissions','Report reason must contain 5-500 characters.'=>'report_reason','Too many reports. Please wait before trying again.'=>'too_many_reports','You already reported this link.'=>'already_reported','APP_KEY is required for Web Links protection.'=>'app_key','Title must contain 2-200 characters.'=>'title_length','Slug must use lowercase words separated by hyphens.'=>'slug','Description is required.'=>'description_required','Description must not exceed 100,000 characters.'=>'description_length','Selected category does not exist.'=>'category_missing','Invalid category.'=>'category_invalid','URL must use safe HTTP or HTTPS without embedded credentials.'=>'url','Image must be a safe path below /uploads/.'=>'image'];return isset($keys[$message])?$this->translator->translate('web-links::error.'.$keys[$message]):$message;}
}
