<?php

declare(strict_types=1);

namespace Modules\WebLinks\src;

use NovaNuke\Core\Membership\MembershipManagerInterface;use PDO;use RuntimeException;

final class WebLinkRepository
{
    private readonly int $perPage;
    public function __construct(private readonly PDO $database,private readonly MembershipManagerInterface $memberships,int $perPage=10){$this->perPage=max(5,min(100,$perPage));}
    public function categories():array{return$this->database->query('SELECT * FROM web_link_categories ORDER BY name')->fetchAll();}
    public function adminLinks():array{return$this->database->query("SELECT l.id,l.title,l.slug,l.status,l.audience,l.is_featured,l.visit_count,l.updated_at,c.name AS category_name,COALESCE(u.username,'Administrator') AS submitter FROM web_links l LEFT JOIN web_link_categories c ON c.id=l.category_id LEFT JOIN users u ON u.id=l.submitted_by WHERE l.deleted_at IS NULL ORDER BY FIELD(l.status,'pending','published','rejected'),l.updated_at DESC")->fetchAll();}
    public function find(int $id):?array{$s=$this->database->prepare('SELECT * FROM web_links WHERE id=:id AND deleted_at IS NULL');$s->execute(compact('id'));$row=$s->fetch();return is_array($row)?$row:null;}
    public function publicBySlug(string $slug):?array{$s=$this->database->prepare("SELECT l.*,c.name AS category_name,c.slug AS category_slug FROM web_links l LEFT JOIN web_link_categories c ON c.id=l.category_id WHERE l.slug=:slug AND l.status='published' AND l.deleted_at IS NULL LIMIT 1");$s->execute(compact('slug'));$row=$s->fetch();return is_array($row)?$row:null;}
    public function catalog(int $page,?string $category,string $search,string $order,?int $userId):array
    {
        $where="l.status='published' AND l.deleted_at IS NULL AND (l.audience='public' OR (:viewer>0 AND l.audience='member') OR (:vip_viewer>0 AND l.audience='vip' AND EXISTS (SELECT 1 FROM user_entitlements ue WHERE ue.user_id=:entitlement_viewer AND ue.entitlement='vip' AND ue.starts_at<=UTC_TIMESTAMP() AND (ue.expires_at IS NULL OR ue.expires_at>UTC_TIMESTAMP()) AND ue.revoked_at IS NULL)))";$params=['viewer'=>$userId??0,'vip_viewer'=>$userId??0,'entitlement_viewer'=>$userId??0];if($category!==null){$where.=' AND c.slug=:category';$params['category']=$category;}if($search!==''){$where.=" AND (l.title LIKE :title ESCAPE '=' OR l.description LIKE :description ESCAPE '=')";$term='%'.strtr($search,['='=>'==','%'=>'=%','_'=>'=_']).'%';$params+=['title'=>$term,'description'=>$term];}
        $count=$this->database->prepare("SELECT COUNT(*) FROM web_links l LEFT JOIN web_link_categories c ON c.id=l.category_id WHERE {$where}");$count->execute($params);$total=(int)$count->fetchColumn();$per=$this->perPage;$pages=max(1,(int)ceil($total/$per));$page=min(max(1,$page),$pages);$orders=['new'=>'l.is_featured DESC,l.created_at DESC,l.id DESC','popular'=>'l.is_featured DESC,l.visit_count DESC,l.id DESC','title'=>'l.is_featured DESC,l.title,l.id'];
        $s=$this->database->prepare("SELECT l.id,l.title,l.slug,l.description,l.description_format,l.image_path,l.is_featured,l.visit_count,l.created_at,c.name AS category_name,c.slug AS category_slug FROM web_links l LEFT JOIN web_link_categories c ON c.id=l.category_id WHERE {$where} ORDER BY ".($orders[$order]??$orders['new']).' LIMIT :limit OFFSET :offset');foreach($params as $k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':limit',$per,PDO::PARAM_INT);$s->bindValue(':offset',($page-1)*$per,PDO::PARAM_INT);$s->execute();return['items'=>$s->fetchAll(),'page'=>$page,'pages'=>$pages,'total'=>$total];
    }
    public function save(?int $id,array $data,?int $submitter):int
    {
        $this->assertCategory($data['category_id']);try{if($id===null){$data['submitted_by']=$submitter;$sql='INSERT INTO web_links (category_id,submitted_by,title,slug,url,description,description_format,image_path,status,audience,is_featured,created_at,updated_at) VALUES (:category_id,:submitted_by,:title,:slug,:url,:description,:description_format,:image_path,:status,:audience,:is_featured,UTC_TIMESTAMP(),UTC_TIMESTAMP())';}else{if($this->find($id)===null)throw new RuntimeException('Link not found.');$data['id']=$id;$sql='UPDATE web_links SET category_id=:category_id,title=:title,slug=:slug,url=:url,description=:description,description_format=:description_format,image_path=:image_path,status=:status,audience=:audience,is_featured=:is_featured,updated_at=UTC_TIMESTAMP() WHERE id=:id AND deleted_at IS NULL';}$this->database->prepare($sql)->execute($data);return$id??(int)$this->database->lastInsertId();}catch(\PDOException $e){if($e->getCode()==='23000')throw new RuntimeException('The link slug is already in use.',0,$e);throw$e;}
    }
    public function canView(array $link,?int $userId):bool{if(($link['audience']??'public')==='public')return true;if($userId===null)return false;if($link['audience']==='member')return true;return$link['audience']==='vip'&&$this->memberships->isVip($userId);}
    public function saveCategory(array $data):int{try{$this->database->prepare('INSERT INTO web_link_categories (name,slug,description,created_at,updated_at) VALUES (:name,:slug,:description,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute($data);return(int)$this->database->lastInsertId();}catch(\PDOException $e){if($e->getCode()==='23000')throw new RuntimeException('The category slug is already in use.',0,$e);throw$e;}}
    public function delete(int $id):void{$s=$this->database->prepare('UPDATE web_links SET deleted_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id AND deleted_at IS NULL');$s->execute(compact('id'));if($s->rowCount()!==1)throw new RuntimeException('Link not found.');}
    public function recordVisit(int $id,string $key):bool{$this->database->beginTransaction();try{$this->database->exec('DELETE FROM web_link_visits WHERE visited_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY)');$s=$this->database->prepare('SELECT COUNT(*) FROM web_link_visits WHERE link_id=:id AND visitor_key=:key AND visited_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 24 HOUR)');$s->execute(compact('id','key'));$counted=(int)$s->fetchColumn()===0;if($counted){$this->database->prepare('INSERT INTO web_link_visits (link_id,visitor_key,visited_at) VALUES (:id,:key,UTC_TIMESTAMP())')->execute(compact('id','key'));$this->database->prepare('UPDATE web_links SET visit_count=visit_count+1 WHERE id=:id')->execute(compact('id'));}$this->database->commit();return$counted;}catch(\Throwable $e){if($this->database->inTransaction())$this->database->rollBack();throw$e;}}
    public function report(int $link,?int $user,string $key,string $reason):void{try{$this->database->prepare("INSERT INTO web_link_reports (link_id,reporter_user_id,reporter_key,reason,status,created_at) VALUES (:link,:user,:key,:reason,'open',UTC_TIMESTAMP())")->execute(compact('link','user','key','reason'));}catch(\PDOException $e){if($e->getCode()==='23000')throw new RuntimeException('You already reported this link.',0,$e);throw$e;}}
    public function reports():array{return$this->database->query("SELECT r.id,r.reason,r.created_at,l.title,COALESCE(u.username,'Guest') AS reporter FROM web_link_reports r INNER JOIN web_links l ON l.id=r.link_id LEFT JOIN users u ON u.id=r.reporter_user_id WHERE r.status='open' ORDER BY r.created_at DESC")->fetchAll();}
    public function resolve(int $id):void{$s=$this->database->prepare("UPDATE web_link_reports SET status='resolved',resolved_at=UTC_TIMESTAMP() WHERE id=:id AND status='open'");$s->execute(compact('id'));if($s->rowCount()!==1)throw new RuntimeException('Open report not found.');}
    private function assertCategory(?int $id):void{if($id===null)return;$s=$this->database->prepare('SELECT COUNT(*) FROM web_link_categories WHERE id=:id');$s->execute(compact('id'));if((int)$s->fetchColumn()!==1)throw new RuntimeException('Selected category does not exist.');}
}
