<?php

declare(strict_types=1);

namespace Modules\WebLinks\src;

use NovaNuke\Core\Admin\AdminMenuBuilding;use NovaNuke\Core\Config\ConfigRepository;use NovaNuke\Core\Container\Container;use NovaNuke\Core\Content\ContentRendererInterface;use NovaNuke\Core\Http\Request;use NovaNuke\Core\Http\Response;use NovaNuke\Core\Modules\ModuleContext;use NovaNuke\Core\Modules\ModuleInterface;use NovaNuke\Core\Security\DatabaseRateLimiter;use NovaNuke\Core\View\ViewRenderer;

final class WebLinksModule implements ModuleInterface
{
    public function register(ModuleContext $context):void{$context->container->get(ViewRenderer::class)->addNamespace('web-links',$context->basePath.'/views');$context->container->get(ViewRenderer::class)->addNamespace('admin-web-links',$context->basePath.'/views/admin');$context->container->bind(WebLinkRepository::class,static fn(Container $c)=>new WebLinkRepository($c->get(\PDO::class),$c->get(\NovaNuke\Core\Membership\MembershipManagerInterface::class),$c->get(\NovaNuke\Core\Settings\SettingsRepository::class)->integer('site.per_page',10,5,100)));$context->container->bind(WebLinkInput::class,static fn()=>new WebLinkInput());$context->container->bind(WebLinkManager::class,static fn(Container $c)=>new WebLinkManager($c->get(WebLinkRepository::class),$c->get(\NovaNuke\Auth\AuthManager::class),new DatabaseRateLimiter($c->get(\PDO::class),5,3600,'web-links-submit'),new DatabaseRateLimiter($c->get(\PDO::class),5,3600,'web-links-report'),(string)$c->get(ConfigRepository::class)->get('app.key','')));}
    public function boot(ModuleContext $context):void
    {
        $context->events->listen(\NovaNuke\Core\Events\EventName::ADMIN_MENU_BUILDING,static function(object $e):void{if($e instanceof AdminMenuBuilding)$e->add('Web Links','/admin/web-links','web-links.manage');});
        $public=static fn(Container $c)=>new PublicWebLinksController($c->get(WebLinkRepository::class),$c->get(WebLinkInput::class),$c->get(WebLinkManager::class),$c->get(\NovaNuke\Auth\AuthManager::class),$c->get(\NovaNuke\Core\Security\CsrfTokenManager::class),$c->get(\NovaNuke\Core\Security\SessionManager::class),$c->get(ViewRenderer::class),$c->get(\NovaNuke\Core\Security\AuthorizationService::class),$c->get(ContentRendererInterface::class),$c->get(\NovaNuke\Core\I18n\Translator::class));$admin=static fn(Container $c)=>new AdminWebLinksController($c->get(WebLinkRepository::class),$c->get(WebLinkInput::class),$c->get(\NovaNuke\Auth\AuthManager::class),$c->get(\NovaNuke\Core\Security\AuthorizationService::class),$c->get(\NovaNuke\Core\Logging\ActivityLogger::class),$c->get(\NovaNuke\Core\Security\CsrfTokenManager::class),$c->get(\NovaNuke\Core\Security\SessionManager::class),$c->get(ViewRenderer::class),$c->get(\NovaNuke\Core\I18n\Translator::class));
        $context->router->get('/links',static fn(Request $r,Container $c):Response=>$public($c)->index($r),'web-links.index');$context->router->get('/links/category/{slug}',static fn(Request $r,Container $c):Response=>$public($c)->index($r,(string)$r->attribute('slug')));$context->router->get('/links/submit',static fn(Request $r,Container $c):Response=>$public($c)->submitForm());$context->router->post('/links/submit',static fn(Request $r,Container $c):Response=>$public($c)->submit($r));$context->router->get('/links/{slug}/visit',static fn(Request $r,Container $c):Response=>$public($c)->visit($r));$context->router->post('/links/{id}/report',static fn(Request $r,Container $c):Response=>$public($c)->report($r));$context->router->get('/links/{slug}',static fn(Request $r,Container $c):Response=>$public($c)->show($r));
        $context->router->get('/admin/web-links',static fn(Request $r,Container $c):Response=>$admin($c)->index());$context->router->get('/admin/web-links/new',static fn(Request $r,Container $c):Response=>$admin($c)->create());$context->router->get('/admin/web-links/{id}/edit',static fn(Request $r,Container $c):Response=>$admin($c)->edit($r));$context->router->post('/admin/web-links/save',static fn(Request $r,Container $c):Response=>$admin($c)->save($r));$context->router->post('/admin/web-links/category',static fn(Request $r,Container $c):Response=>$admin($c)->category($r));$context->router->post('/admin/web-links/{id}/delete',static fn(Request $r,Container $c):Response=>$admin($c)->delete($r));$context->router->post('/admin/web-link-reports/{id}/resolve',static fn(Request $r,Container $c):Response=>$admin($c)->resolve($r));
    }
}
