<?php

declare(strict_types=1);

namespace Modules\Polls\src;

use NovaNuke\Auth\AuthManager;use NovaNuke\Core\Http\Request;use NovaNuke\Core\Http\Response;use NovaNuke\Core\I18n\Translator;use NovaNuke\Core\Logging\ActivityLogger;use NovaNuke\Core\Security\AuthorizationService;use NovaNuke\Core\Security\CsrfTokenManager;use NovaNuke\Core\Security\SessionManager;use NovaNuke\Core\View\ViewRenderer;use RuntimeException;

final class AdminPollsController
{
    public function __construct(private readonly PollRepository $polls,private readonly PollInput $input,private readonly AuthManager $auth,private readonly AuthorizationService $authorization,private readonly ActivityLogger $activity,private readonly CsrfTokenManager $csrf,private readonly SessionManager $session,private readonly ViewRenderer $views,private readonly Translator $translator){}
    public function index(Request $request):Response{if($g=$this->guard())return$g;$edit=null;$id=filter_var($request->query('edit'),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($id)$edit=$this->polls->find((int)$id);return$this->view($edit);}
    public function save(Request $request):Response{if($g=$this->guard())return$g;if(!$this->csrf->validate($request->input('_token')))return Response::html($this->translator->translate('polls::error.csrf'),419);try{$actor=$this->auth->user();$id=filter_var($request->input('id'),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:null;$poll=$this->polls->save($id?(int)$id:null,$this->input->poll($request->allInput()),(int)$actor['id']);$this->activity->log((int)$actor['id'],'poll.saved','poll',$poll,[],$request->ip());$this->session->put('polls.admin.message',$this->translator->translate('polls::admin.message.saved'));return Response::redirect('/admin/polls',303);}catch(RuntimeException $e){return$this->view($request->allInput(),$this->error($e->getMessage()),422);}}
    public function delete(Request $request):Response{if($g=$this->guard())return$g;if(!$this->csrf->validate($request->input('_token')))return Response::html($this->translator->translate('polls::error.csrf'),419);try{$id=$this->id($request->attribute('id'));if($request->input('confirm_delete')!=='1')throw new RuntimeException('Confirm poll deletion.');$this->polls->delete($id);$actor=$this->auth->user();$this->activity->log((int)$actor['id'],'poll.deleted','poll',$id,[],$request->ip());$this->session->put('polls.admin.message',$this->translator->translate('polls::admin.message.deleted'));}catch(RuntimeException $e){$this->session->put('polls.admin.error',$this->error($e->getMessage()));}return Response::redirect('/admin/polls',303);}
    private function view(?array $edit=null,?string $error=null,int $status=200):Response{return Response::html($this->views->render('@polls/admin/index.twig',['polls'=>$this->polls->all(),'edit'=>$edit,'csrf_token'=>$this->csrf->token(),'message'=>$this->session->pull('polls.admin.message'),'error'=>$error??$this->session->pull('polls.admin.error')]),$status);}
    private function guard():?Response{$u=$this->auth->user();if($u===null)return Response::redirect('/login');return$this->authorization->allows((int)$u['id'],'polls.manage')?null:Response::html($this->translator->translate('polls::admin.error.forbidden'),403);}
    private function id(mixed $v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($id===false)throw new RuntimeException('Invalid poll.');return(int)$id;}
    private function error(string$message):string{$keys=['Poll not found.'=>'not_found','Invalid poll.'=>'invalid','Confirm poll deletion.'=>'confirm_delete','Options cannot be changed after voting begins.'=>'options_locked','Question must contain 5-300 characters.'=>'question_length','Invalid poll status.'=>'invalid_status','Poll options must be unique.'=>'options_unique','Provide 2-20 unique options.'=>'options_count','Poll options cannot exceed 200 characters.'=>'option_length','The end date must be later than the start date.'=>'date_order','Invalid poll date.'=>'invalid_date'];return isset($keys[$message])?$this->translator->translate('polls::admin.error.'.$keys[$message]):$message;}
}
